# Generated by Django 3.0.8 on 2020-07-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='note',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
